In [2]:
import pandas as pd

In [5]:
df = pd.read_csv("../data/destination_raw.csv")
df.head(10)

,place_name,description,category,city,estimated_cost,popular_activities,best_season,duration_days
0,Destination 1,Lakeside city known for Phewa Lake and as a ga...,Nature,Pokhara,3500,"Boating, Paragliding, Hiking",September to November,3
1,Destination 2,"Historic square with palaces, courtyards and t...",Cultural,Kathmandu,1500,"Sightseeing, Photography",October to December,1
2,Destination 3,UNESCO World Heritage Site and one of the holi...,Religious,Kathmandu,1000,"Pilgrimage, Cultural Visit",February to April,1
3,Destination 4,"Jungle safari destination known for rhinos, ti...",Wildlife,Chitwan,4000,"Jungle Safari, Elephant Ride, Canoeing",October to March,2
4,Destination 5,Birthplace of Lord Buddha and UNESCO World Her...,Religious,Lumbini,2000,"Pilgrimage, Monastery Tour",October to December,2
5,Destination 6,Beautiful wildlife spot located in Pokhara. Kn...,Wildlife,Pokhara,2187,Photography,March to May,2
6,Destination 7,Beautiful nature spot located in Pokhara. Know...,Nature,Pokhara,1166,Paragliding,March to May,2
7,Destination 8,Beautiful nature spot located in Namche Bazaar...,Nature,Namche Bazaar,4922,Trekking,September to November,2
8,Destination 9,Beautiful wildlife spot located in Jomsom. Kno...,Wildlife,Jomsom,2538,Sightseeing,October to December,2
9,Destination 10,Beautiful wildlife spot located in Dhulikhel. ...,Wildlife,Dhulikhel,1581,Hiking,September to November,2

In [6]:
df= df.applymap(lambda x: x.strip() if isinstance(x,str) else x )
print(df.isnull().sum())

place_name            0
description           0
category              0
city                  0
estimated_cost        0
popular_activities    0
best_season           0
duration_days         0
dtype: int64

C:\Users\Dell\AppData\Local\Temp\ipykernel_7232\3801332358.py:1: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  df= df.applymap(lambda x: x.strip() if isinstance(x,str) else x )

In [7]:
print(df['category'].value_counts())

category
Cultural     22
Wildlife     22
Religious    22
Nature       21
Adventure    14
Name: count, dtype: int64

In [8]:
df.to_csv('../data/cleaned_destinations.csv', index=False)